# Generated by Django 4.0.6 on 2022-09-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASGMElisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=3000)),
                ('two', models.CharField(max_length=3000)),
                ('three', models.CharField(max_length=3000)),
                ('four', models.CharField(max_length=3000)),
                ('five', models.CharField(max_length=3000)),
                ('six', models.CharField(max_length=3000)),
                ('seven', models.CharField(max_length=3000)),
                ('eight', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Cement',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='fill here', max_length=250)),
                ('Title', models.TextField(default='fill here', max_length=250)),
                ('Mailing_address', models.TextField(default='fill here', max_length=250, verbose_name='Mailing address')),
                ('Mobile', models.TextField(default='fill here', max_length=250)),
                ('Alternate_mobile', models.TextField(default='fill here', max_length=250, verbose_name='Alternate mobile number')),
                ('email', models.TextField(default='fill here', max_length=250)),
                ('Alternate_email', models.TextField(default='fill here', max_length=250, verbose_name='Alternate email')),
                ('Web_page', models.TextField(default='fill here', max_length=250, verbose_name='Web page')),
            ],
        ),
        migrations.CreateModel(
            name='dpcmmis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Any_improvements_for_the_next_version_of_mmis', models.TextField(default='fill here', max_length=500, verbose_name='What suggestions do you have to improve the next version of the Mercury Management Information System?')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumptionAndFuelProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Energy Consumption & Fuel Production',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentAndHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(default='fill here', max_length=3000, verbose_name='What measures are taken to inform the public on exposure to mercury?')),
                ('two', models.CharField(default='fill here', max_length=3000, verbose_name='What measures are in place to project human health from mercury contamination?')),
                ('three', models.CharField(default='fill here', max_length=3000, verbose_name='What measures are in place to project human health from mercury contamination?')),
            ],
        ),
        migrations.CreateModel(
            name='MercuryAddedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Mercury Added Products',
            },
        ),
        migrations.CreateModel(
            name='MercurySupplySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_primary_mines_if_any', models.TextField(default='fill here', max_length=3000, verbose_name='Give details of any primary mercury mines thatare now in operation, if any?')),
                ('State_mercury_importation_for_products', models.TextField(default='fill here', max_length=300, verbose_name='Give details of mercury importation source for products')),
                ('Any_excess_mercury_available_from_decommissioning_of_products', models.TextField(default='fill here', max_length=3000, verbose_name='Give details of excess mercury available from decommissioning of products')),
                ('Any_mercury_added_products', models.TextField(default='fill here', max_length=3000, verbose_name='Give details of any mercury added products')),
                ('Any_measures_to_achieve_reductions_in_mercury_use', models.TextField(default='fill here', max_length=3000, verbose_name='What measures are in place to achieve reductions in mercury use?')),
                ('State_measures_taken_to_address_mercury_emission_and_releases', models.TextField(default='fill here', max_length=3000, verbose_name='State measures taken to address mercury emission and releases')),
                ('State_estimated_yearly_amount_of_mercury_compounds_used', models.TextField(default='fill here', max_length=3000, verbose_name='State estimated yearly amount of mercury compounds used')),
                ('Any_measures_to_restrict_the_use_of_mercury_products', models.TextField(default='fill here', max_length=3000, verbose_name='Are there any measures to restrict the use of mercury products?')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('Full_address', models.CharField(max_length=200, verbose_name='Complete Address')),
                ('Mercury_Supply_Source', models.TextField(max_length=250, verbose_name='Mercury Supply Source')),
                ('Product', models.TextField(max_length=250, verbose_name='Product')),
                ('Date_of_manufacture_commencement', models.DateTimeField(verbose_name='Date of manufacture commencement')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.BooleanField()),
                ('shipping_destination', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Any_interim_storage_of_non_waste_mercury_compounds', models.CharField(default='fill here', max_length=3000, verbose_name='Are there any interim storage of non-waste mercury compounds?')),
                ('Explain_how_effective_the_storage_is_environmentally', models.CharField(default='fill here', max_length=3000, verbose_name='Explain how effective the storage is environmentally')),
                ('Any_facility_for_final_disposal_of_mercury_compound_waste', models.CharField(default='fill here', max_length=3000, verbose_name='Are there any facility for final disposal of mercury compound waste?')),
            ],
        ),
    ]
