# Generated by Django 4.0.3 on 2022-03-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_party', models.CharField(max_length=50)),
                ('Industry', models.TextField(max_length=50)),
                ('Date_on_which_its_instrument_of_ratification', models.DateTimeField()),
                ('Location', models.TextField(max_length=50)),
            ],
        ),
    ]
