# Generated by Django 4.0.6 on 2022-09-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asgmelisha',
            table='ASGM',
        ),
    ]
