# Generated by Django 4.0.3 on 2022-03-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='dpcmmis',
        ),
    ]
