# Generated by Django 4.0.6 on 2022-09-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0002_alter_asgmelisha_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asgmelisha',
            table='ASGMElisha',
        ),
    ]
