# Generated by Django 4.0.3 on 2022-03-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0003_rename_dpcmmis_mmisdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mmisdetail',
            new_name='dpcmmis',
        ),
    ]
