# Generated by Django 4.0.3 on 2022-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0004_rename_mmisdetail_dpcmmis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_the_possible_challenges_in_meeting_the_objective_of_the_convention', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Title', models.TextField(max_length=50)),
                ('Mailing_address', models.TextField(max_length=50)),
                ('Mobile', models.TextField(max_length=50)),
                ('Alternate_mobile', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('Alternate_email', models.TextField(max_length=50)),
                ('Web_page', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_measures_taken_to_inform_the_public_on_exposure_to_mecury', models.TextField(max_length=50)),
                ('State_measures_taken_to_protect_human_health', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mercury_Supply_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_primary_mines_if_any', models.CharField(max_length=50)),
                ('State_mercury_importation_for_products', models.TextField(max_length=50)),
                ('Any_excess_mercury_available_from_decomissioning_of_products', models.TextField(max_length=50)),
                ('Any_mercury_added_products', models.TextField(max_length=50)),
                ('Any_measures_to_achieve_reductions_in_mercury_use', models.TextField(max_length=50)),
                ('State_measures_taken_to_address_mercury_emission_and_releases', models.TextField(max_length=50)),
                ('State_estimated_yearly_amount_of_mercury_or_mercury_compounds_used', models.TextField(max_length=50)),
                ('Any_measures_to_restrict_the_use_of_mercury_or_mercury_products', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Full_address', models.CharField(max_length=200)),
                ('Mercury_Supply_Source', models.TextField(max_length=150)),
                ('Product', models.TextField(max_length=50)),
                ('Date_of_manufacture_commencement', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Any_interim_storage_of_non_waste_mercury_and_mercury_compounds', models.TextField(max_length=50)),
                ('Explain_how_effective_the_storage_is_environmentally', models.TextField(max_length=50)),
                ('Any_facility_for_final_disposal_of_mercury_or_mercury_compound_waste', models.TextField(max_length=50)),
            ],
        ),
    ]
