# Generated by Django 4.0.3 on 2022-04-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0007_remove_c_mercury_supply_source_any_measures_to_restrict_the_use_of_mercury_or_mercury_products_and_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_organization',
            name='Date_of_manufacture_commencement',
            field=models.DateTimeField(verbose_name='Date of manufacture commencement'),
        ),
        migrations.AlterField(
            model_name='a_organization',
            name='Full_address',
            field=models.CharField(max_length=200, verbose_name='Complete Address'),
        ),
        migrations.AlterField(
            model_name='a_organization',
            name='Mercury_Supply_Source',
            field=models.TextField(max_length=250, verbose_name='Mercury Supply Source'),
        ),
        migrations.AlterField(
            model_name='a_organization',
            name='Name',
            field=models.CharField(max_length=250, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='a_organization',
            name='Product',
            field=models.TextField(max_length=250, verbose_name='Product'),
        ),
    ]
