# Generated by Django 4.0.3 on 2022-04-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpcmmis', '0008_alter_a_organization_date_of_manufacture_commencement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='b_ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='fill here', max_length=250)),
                ('Title', models.TextField(default='fill here', max_length=250)),
                ('Mailing_address', models.TextField(default='fill here', max_length=250, verbose_name='Mailing address')),
                ('Mobile', models.TextField(default='fill here', max_length=250)),
                ('Alternate_mobile', models.TextField(default='fill here', max_length=250, verbose_name='Alternate mobile number')),
                ('email', models.TextField(default='fill here', max_length=250)),
                ('Alternate_email', models.TextField(default='fill here', max_length=250, verbose_name='Alternate email')),
                ('Web_page', models.TextField(default='fill here', max_length=250, verbose_name='Web page')),
            ],
        ),
        migrations.CreateModel(
            name='c_MercurySupplySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_primary_mines_if_any', models.CharField(default='fill here', max_length=300, verbose_name='Give details of any primary mercury mines thatare now in operation, if any?')),
                ('State_mercury_importation_for_products', models.CharField(default='fill here', max_length=300, verbose_name='Give details of mercury importation source for products')),
                ('Any_excess_mercury_available_from_decomissioning_of_products', models.CharField(default='fill here', max_length=300, verbose_name='Give details of excess mercury available from decommissioning of products')),
                ('Any_mercury_added_products', models.CharField(default='fill here', max_length=300, verbose_name='Give details of any mercury added products')),
                ('Any_measures_to_achieve_reductions_in_mercury_use', models.CharField(default='fill here', max_length=300, verbose_name='What measures are in place to achieve reductions in mercury use?')),
                ('State_measures_taken_to_address_mercury_emission_and_releases', models.CharField(default='fill here', max_length=300, verbose_name='State measures taken to address mercury emission and releases')),
                ('State_estimated_yearly_amount_of_mercury_compounds_used', models.CharField(default='fill here', max_length=300, verbose_name='State estimated yearly amount of mercury compounds used')),
                ('Any_measures_to_restrict_the_use_of_mercury_products', models.CharField(default='fill here', max_length=300, verbose_name='Are there any measures to restrict the use of mercury products?')),
            ],
        ),
        migrations.DeleteModel(
            name='b_Contact_Person',
        ),
        migrations.DeleteModel(
            name='c_Mercury_Supply_Source',
        ),
        migrations.AlterField(
            model_name='d_waste',
            name='Any_facility_for_final_disposal_of_mercury_compound_waste',
            field=models.CharField(default='fill here', max_length=300, verbose_name='Are there any facility for final disposal of mercury compound waste?'),
        ),
        migrations.AlterField(
            model_name='d_waste',
            name='Any_interim_storage_of_non_waste_mercury_compounds',
            field=models.CharField(default='fill here', max_length=300, verbose_name='Are there any interim storate of non-waste mercury compounds?'),
        ),
        migrations.AlterField(
            model_name='d_waste',
            name='Explain_how_effective_the_storage_is_environmentally',
            field=models.CharField(default='fill here', max_length=300, verbose_name='Explain how effective the storage is environmentally'),
        ),
        migrations.AlterField(
            model_name='e_health',
            name='Any_measures_taken_to_inform_the_public_on_exposure_to_mecury',
            field=models.CharField(default='fill here', max_length=300, verbose_name='What measures are taken to inform the public on exposure to mercury?'),
        ),
        migrations.AlterField(
            model_name='e_health',
            name='Any_measures_taken_to_protect_human_health',
            field=models.CharField(default='fill here', max_length=300, verbose_name='What measures are in place to project human health from mercury contamination?'),
        ),
        migrations.AlterField(
            model_name='f_challenges',
            name='Any_possible_challenges_in_meeting_convention_objectives',
            field=models.CharField(default='fill here', max_length=300, verbose_name='What are the possible challenges in meeting mercury convention objectives?'),
        ),
        migrations.AlterField(
            model_name='g_dpcmmis',
            name='Any_improvements_for_the_next_version_of_mmis',
            field=models.TextField(default='fill here', max_length=500, verbose_name='What suggestions do you have to improve the next version of the Mercury Management Information System?'),
        ),
    ]
